config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#home"

  resources :passwords, params: :token
  resource :session

  scope :admin, module: :admins do
    root to: "static_pages#top", as: :admin_root
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/admins/application_controller.rb
class Admins::ApplicationController < ApplicationController
end

app/controllers/admins/static_pages_controller.rb
class Admins::StaticPagesController < Admins::ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern unless ENV.fetch("RAILS_ENV", "development") == "development"
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "しばらく待ってからやり直してください。" }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "ログインに失敗しました"
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  allow_unauthenticated_access

  def home
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/static_pages/top.html.slim
h1 管理画面
| 管理画面のトップページです。

h2 メニュー
ul 
  li = link_to "ログアウト", session_path, data: { turbo_method: :delete, turbo_confirm: "ログアウトします" }

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for(:title) || "βインディの星明かり"
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    meta[name="apple-mobile-web-app-capable" content="yes"]
    meta[name="mobile-web-app-capable" content="yes"]
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    - # Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!)
    - #= tag.link rel: "manifest", href: pwa_manifest_path(format: :json)
    = favicon_link_tag "favicon.ico"
    - # Includes all stylesheet files in app/assets/stylesheets
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    
    = javascript_importmap_tags
  header class="h-28 bg-lime-400 flex flex-col items-start space-y-2 mb-4"
    .flex.items-center.space-x-4.mb-0
      = image_tag "logo.png", alt: "beta-indus", class: "h-20"
      = link_to "Beta Indus", root_path, class: "text-4xl header_link"

    nav class="w-full bg-yellow-300 p-1"
      ul class="flex ms-4 space-x-4"
        li = link_to "ホーム", root_path, class: "header_link"
        - if authenticated?
          li = link_to "管理画面", admin_root_path, class: "header_link"
  body
    main class="container mx-auto px-5"
      = yield

app/views/static_pages/home.html.slim
div
  h1 βインディの星明かり
  p
    | βインディがRailsで作成したホームページです。
  
  h2 ロゴマーク
  = image_tag "logo.png", alt: "βインディのロゴマーク"

  h2 SNSについて
  p 
    = link_to "Xのアカウント(@beta_indus)", "https://x.com/beta_indus" 
    | を持っています。フォロー等お待ちしております。
    